paths:
  data_dir: "C:/My folder/pokedex-main"
  model_dir: "./models"
  output_dir: "./outputs"

training:
  num_epochs: 200
  batch_size: 8
  learning_rate: 1e-4
  save_interval: 50
  best_model_epoch_threshold: 10

model:
  text_embed_dim: 256
  num_heads: 4
  decoder_depth: 5
  latent_size: [512, 8, 8]
  output_size: [3, 128, 128]
  sequence_length: 168
