paths:
  data_dir: "C:/My folder/pokedex-main"
  model_dir: "./models"
  output_dir: "./outputs"

training:
  num_epochs: 100
  batch_size: 4
  learning_rate: 4e-4
  save_interval: 50
  best_model_epoch_threshold: 10

model:
  text_embed_dim: 256
  num_heads: 8
  decoder_depth: 2
  latent_size: [ 512, 32, 32 ]
  output_size: [3, 128, 128]
  sequence_length: 168
