paths:
  data_dir: "C:/My folder/pokedex-main"
  model_dir: "./models"
  output_dir: "./outputs"

training:
  num_epochs: 100
  batch_size: 4
  learning_rate: 4e-4
  save_interval: 50
  best_model_epoch_threshold: 10
  images: 200

model:
  text_embed_dim: 256
  num_heads: 4
  decoder_depth: 3
  latent_size: [ 256, 4, 4 ]
  output_size: [ 3, 215, 215 ]
  sequence_length: 168
